INSERT INTO zapzup.user_entity (id,
                                name,
                                username,
                                email,
                                status,
                                note,
                                password,
                                created_at,
                                updated_at,
                                deleted_at)
VALUES ('USER-ID',
        'Fulano',
        'Fulaninho',
        'fulano@gmail.com',
        'ACTIVE',
        'Hello!',
        '$2a$10$dW9XpjFKA5FLEpZrN/w1a.edV7R3r02ZT3XpPluGDWae8tXvmQCKy',
        current_timestamp,
        null,
        null);